name: furniture_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  animate_do: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/box_colors/
    - assets/images/categories/
    - assets/svg/

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Black.ttf
            weight: 900
          - asset: assets/fonts/Poppins-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300
          - asset: assets/fonts/Poppins-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Poppins-Thin.ttf
            weight: 100

